version: "3.9"
services:
  db:
    container_name: "newsletter-db"
    image: postgres:13
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  api:
    container_name: "newsletter-api"
    build: .
    ports:
      - "8000:8000"
    environment:
      - "APP_ENVIRONMENT=production"
    depends_on:
      - db